language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    #- LUA=lua5.3 (luacrypto does not support Lua 5.3 yet)
    - LUA=luajit     # latest stable version (2.0.3)
    - LUA=luajit2.0  # current head of 2.0 branch
    - LUA=luajit2.1  # current head of 2.1 branch

matrix:
  include:
    - env: LUA=lua5.1 LUANODE=true
      sudo: true

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install lunit
  - luarocks install luacrypto
  - luarocks install http://luarocks.org/repositories/rocks-scm/luasocket-3.0rc1-1.rockspec
  - luarocks install lbase64
  - luarocks install http://luarocks.org/repositories/rocks-scm/luasec-scm-1.rockspec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu

script:
  - if [ "$LUANODE" = "true" ]; then
      cd unittest/luanode && ./run.sh;
    else
      cd unittest && lua run.lua;
    fi
